development:
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME", "ddh2buclq") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY", "") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET", "") %>
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME", "ddh2buclq") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY") { Rails.application.credentials.dig(:cloudinary, :api_key) } %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET") { Rails.application.credentials.dig(:cloudinary, :api_secret) } %>
  enhance_image_tag: true
  static_file_support: false

test:
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME", "ddh2buclq") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY", "") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET", "") %>
  enhance_image_tag: true
  static_file_support: false

